// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
	"github.com/shopspring/decimal"
)

const getBusinessUnits = `-- name: GetBusinessUnits :many
SELECT DISTINCT business_unit
FROM jobs
WHERE business_unit IS NOT NULL
ORDER BY business_unit
`

// Lists all unique business units
func (q *Queries) GetBusinessUnits(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getBusinessUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var business_unit sql.NullString
		if err := rows.Scan(&business_unit); err != nil {
			return nil, err
		}
		items = append(items, business_unit)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDateRangeBounds = `-- name: GetDateRangeBounds :one
SELECT 
    MIN(job_completion_date) as earliest_date,
    MAX(job_completion_date) as latest_date
FROM jobs
WHERE job_completion_date IS NOT NULL
  AND status = 'Completed'
`

type GetDateRangeBoundsRow struct {
	EarliestDate interface{} `json:"earliest_date"`
	LatestDate   interface{} `json:"latest_date"`
}

// Gets the earliest and latest job completion dates
func (q *Queries) GetDateRangeBounds(ctx context.Context) (GetDateRangeBoundsRow, error) {
	row := q.db.QueryRowContext(ctx, getDateRangeBounds)
	var i GetDateRangeBoundsRow
	err := row.Scan(&i.EarliestDate, &i.LatestDate)
	return i, err
}

const getJobTechniciansForAnalytics = `-- name: GetJobTechniciansForAnalytics :many
SELECT 
    jt.job_id,
    jt.technician_id,
    t.name as technician_name,
    jt.role
FROM job_technicians jt
JOIN technicians t ON t.id = jt.technician_id
`

type GetJobTechniciansForAnalyticsRow struct {
	JobID          string `json:"job_id"`
	TechnicianID   int64  `json:"technician_id"`
	TechnicianName string `json:"technician_name"`
	Role           string `json:"role"`
}

// Fetches all job-technician relationships with technician names
func (q *Queries) GetJobTechniciansForAnalytics(ctx context.Context) ([]GetJobTechniciansForAnalyticsRow, error) {
	rows, err := q.db.QueryContext(ctx, getJobTechniciansForAnalytics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetJobTechniciansForAnalyticsRow{}
	for rows.Next() {
		var i GetJobTechniciansForAnalyticsRow
		if err := rows.Scan(
			&i.JobID,
			&i.TechnicianID,
			&i.TechnicianName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobTechniciansForAnalyticsByJobs = `-- name: GetJobTechniciansForAnalyticsByJobs :many
SELECT 
    jt.job_id,
    jt.technician_id,
    t.name as technician_name,
    jt.role
FROM job_technicians jt
JOIN technicians t ON t.id = jt.technician_id
WHERE jt.job_id = ANY($1::text[])
`

type GetJobTechniciansForAnalyticsByJobsRow struct {
	JobID          string `json:"job_id"`
	TechnicianID   int64  `json:"technician_id"`
	TechnicianName string `json:"technician_name"`
	Role           string `json:"role"`
}

// Fetches job-technician relationships for specific jobs
func (q *Queries) GetJobTechniciansForAnalyticsByJobs(ctx context.Context, dollar_1 []string) ([]GetJobTechniciansForAnalyticsByJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, getJobTechniciansForAnalyticsByJobs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetJobTechniciansForAnalyticsByJobsRow{}
	for rows.Next() {
		var i GetJobTechniciansForAnalyticsByJobsRow
		if err := rows.Scan(
			&i.JobID,
			&i.TechnicianID,
			&i.TechnicianName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobsForAnalytics = `-- name: GetJobsForAnalytics :many

SELECT 
    j.id,
    j.project_id,
    j.status,
    j.job_completion_date,
    j.business_unit,
    j.total_hours_worked,
    COALESCE(j.estimate_count, 0) as estimate_count,
    j.estimate_sales_subtotal,
    j.assigned_technician,
    j.warranty,
    j.warranty_for_job_id,
    j.recall,
    j.recall_for_job_id
FROM jobs j
WHERE j.status = 'Completed'
ORDER BY j.job_completion_date DESC
`

type GetJobsForAnalyticsRow struct {
	ID                    string          `json:"id"`
	ProjectID             sql.NullString  `json:"project_id"`
	Status                string          `json:"status"`
	JobCompletionDate     sql.NullTime    `json:"job_completion_date"`
	BusinessUnit          sql.NullString  `json:"business_unit"`
	TotalHoursWorked      decimal.Decimal `json:"total_hours_worked"`
	EstimateCount         int32           `json:"estimate_count"`
	EstimateSalesSubtotal decimal.Decimal `json:"estimate_sales_subtotal"`
	AssignedTechnician    sql.NullString  `json:"assigned_technician"`
	Warranty              bool            `json:"warranty"`
	WarrantyForJobID      sql.NullString  `json:"warranty_for_job_id"`
	Recall                bool            `json:"recall"`
	RecallForJobID        sql.NullString  `json:"recall_for_job_id"`
}

// Analytics queries - raw data only, no aggregations
// All calculations done in Go
// Fetches raw job data for analytics calculations
func (q *Queries) GetJobsForAnalytics(ctx context.Context) ([]GetJobsForAnalyticsRow, error) {
	rows, err := q.db.QueryContext(ctx, getJobsForAnalytics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetJobsForAnalyticsRow{}
	for rows.Next() {
		var i GetJobsForAnalyticsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Status,
			&i.JobCompletionDate,
			&i.BusinessUnit,
			&i.TotalHoursWorked,
			&i.EstimateCount,
			&i.EstimateSalesSubtotal,
			&i.AssignedTechnician,
			&i.Warranty,
			&i.WarrantyForJobID,
			&i.Recall,
			&i.RecallForJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobsForAnalyticsByBusinessUnit = `-- name: GetJobsForAnalyticsByBusinessUnit :many
SELECT 
    j.id,
    j.project_id,
    j.status,
    j.job_completion_date,
    j.business_unit,
    j.total_hours_worked,
    COALESCE(j.estimate_count, 0) as estimate_count,
    j.estimate_sales_subtotal,
    j.assigned_technician,
    j.warranty,
    j.warranty_for_job_id,
    j.recall,
    j.recall_for_job_id
FROM jobs j
WHERE j.status = 'Completed'
  AND j.business_unit = $1
ORDER BY j.job_completion_date DESC
`

type GetJobsForAnalyticsByBusinessUnitRow struct {
	ID                    string          `json:"id"`
	ProjectID             sql.NullString  `json:"project_id"`
	Status                string          `json:"status"`
	JobCompletionDate     sql.NullTime    `json:"job_completion_date"`
	BusinessUnit          sql.NullString  `json:"business_unit"`
	TotalHoursWorked      decimal.Decimal `json:"total_hours_worked"`
	EstimateCount         int32           `json:"estimate_count"`
	EstimateSalesSubtotal decimal.Decimal `json:"estimate_sales_subtotal"`
	AssignedTechnician    sql.NullString  `json:"assigned_technician"`
	Warranty              bool            `json:"warranty"`
	WarrantyForJobID      sql.NullString  `json:"warranty_for_job_id"`
	Recall                bool            `json:"recall"`
	RecallForJobID        sql.NullString  `json:"recall_for_job_id"`
}

// Fetches raw job data filtered by business unit
func (q *Queries) GetJobsForAnalyticsByBusinessUnit(ctx context.Context, businessUnit sql.NullString) ([]GetJobsForAnalyticsByBusinessUnitRow, error) {
	rows, err := q.db.QueryContext(ctx, getJobsForAnalyticsByBusinessUnit, businessUnit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetJobsForAnalyticsByBusinessUnitRow{}
	for rows.Next() {
		var i GetJobsForAnalyticsByBusinessUnitRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Status,
			&i.JobCompletionDate,
			&i.BusinessUnit,
			&i.TotalHoursWorked,
			&i.EstimateCount,
			&i.EstimateSalesSubtotal,
			&i.AssignedTechnician,
			&i.Warranty,
			&i.WarrantyForJobID,
			&i.Recall,
			&i.RecallForJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobsForAnalyticsByDateRange = `-- name: GetJobsForAnalyticsByDateRange :many
SELECT 
    j.id,
    j.project_id,
    j.status,
    j.job_completion_date,
    j.business_unit,
    j.total_hours_worked,
    COALESCE(j.estimate_count, 0) as estimate_count,
    j.estimate_sales_subtotal,
    j.assigned_technician,
    j.warranty,
    j.warranty_for_job_id,
    j.recall,
    j.recall_for_job_id
FROM jobs j
WHERE j.status = 'Completed'
  AND j.job_completion_date >= $1
  AND j.job_completion_date <= $2
ORDER BY j.job_completion_date DESC
`

type GetJobsForAnalyticsByDateRangeParams struct {
	JobCompletionDate   sql.NullTime `json:"job_completion_date"`
	JobCompletionDate_2 sql.NullTime `json:"job_completion_date_2"`
}

type GetJobsForAnalyticsByDateRangeRow struct {
	ID                    string          `json:"id"`
	ProjectID             sql.NullString  `json:"project_id"`
	Status                string          `json:"status"`
	JobCompletionDate     sql.NullTime    `json:"job_completion_date"`
	BusinessUnit          sql.NullString  `json:"business_unit"`
	TotalHoursWorked      decimal.Decimal `json:"total_hours_worked"`
	EstimateCount         int32           `json:"estimate_count"`
	EstimateSalesSubtotal decimal.Decimal `json:"estimate_sales_subtotal"`
	AssignedTechnician    sql.NullString  `json:"assigned_technician"`
	Warranty              bool            `json:"warranty"`
	WarrantyForJobID      sql.NullString  `json:"warranty_for_job_id"`
	Recall                bool            `json:"recall"`
	RecallForJobID        sql.NullString  `json:"recall_for_job_id"`
}

// Fetches raw job data within a date range
func (q *Queries) GetJobsForAnalyticsByDateRange(ctx context.Context, arg GetJobsForAnalyticsByDateRangeParams) ([]GetJobsForAnalyticsByDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getJobsForAnalyticsByDateRange, arg.JobCompletionDate, arg.JobCompletionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetJobsForAnalyticsByDateRangeRow{}
	for rows.Next() {
		var i GetJobsForAnalyticsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Status,
			&i.JobCompletionDate,
			&i.BusinessUnit,
			&i.TotalHoursWorked,
			&i.EstimateCount,
			&i.EstimateSalesSubtotal,
			&i.AssignedTechnician,
			&i.Warranty,
			&i.WarrantyForJobID,
			&i.Recall,
			&i.RecallForJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTechnicianByID = `-- name: GetTechnicianByID :one
SELECT 
    t.id,
    t.name,
    (
        SELECT j.business_unit 
        FROM job_technicians jt
        JOIN jobs j ON j.id = jt.job_id
        WHERE jt.technician_id = t.id 
          AND j.business_unit IS NOT NULL
        GROUP BY j.business_unit
        ORDER BY COUNT(*) DESC
        LIMIT 1
    ) as business_unit
FROM technicians t
WHERE t.id = $1
`

type GetTechnicianByIDRow struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	BusinessUnit sql.NullString `json:"business_unit"`
}

func (q *Queries) GetTechnicianByID(ctx context.Context, id int64) (GetTechnicianByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTechnicianByID, id)
	var i GetTechnicianByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.BusinessUnit)
	return i, err
}

const getTechniciansForAnalytics = `-- name: GetTechniciansForAnalytics :many
SELECT 
    t.id,
    t.name,
    (
        SELECT j.business_unit 
        FROM job_technicians jt
        JOIN jobs j ON j.id = jt.job_id
        WHERE jt.technician_id = t.id 
          AND j.business_unit IS NOT NULL
        GROUP BY j.business_unit
        ORDER BY COUNT(*) DESC
        LIMIT 1
    ) as business_unit
FROM technicians t
ORDER BY t.name
`

type GetTechniciansForAnalyticsRow struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	BusinessUnit sql.NullString `json:"business_unit"`
}

// Fetches all technicians with their most common business unit
func (q *Queries) GetTechniciansForAnalytics(ctx context.Context) ([]GetTechniciansForAnalyticsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTechniciansForAnalytics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTechniciansForAnalyticsRow{}
	for rows.Next() {
		var i GetTechniciansForAnalyticsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.BusinessUnit); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
