// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: import_batches.sql

package db

import (
	"context"
	"database/sql"
)

const createImportBatch = `-- name: CreateImportBatch :one
INSERT INTO import_batches (
    job_report_filename,
    invoice_report_filename,
    job_report_hash,
    invoice_report_hash,
    row_count_jobs,
    row_count_invoices,
    status
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, job_report_filename, invoice_report_filename, job_report_hash, invoice_report_hash, imported_at, row_count_jobs, row_count_invoices, status, error_message, created_at
`

type CreateImportBatchParams struct {
	JobReportFilename     string `json:"job_report_filename"`
	InvoiceReportFilename string `json:"invoice_report_filename"`
	JobReportHash         string `json:"job_report_hash"`
	InvoiceReportHash     string `json:"invoice_report_hash"`
	RowCountJobs          int32  `json:"row_count_jobs"`
	RowCountInvoices      int32  `json:"row_count_invoices"`
	Status                string `json:"status"`
}

func (q *Queries) CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (ImportBatch, error) {
	row := q.db.QueryRowContext(ctx, createImportBatch,
		arg.JobReportFilename,
		arg.InvoiceReportFilename,
		arg.JobReportHash,
		arg.InvoiceReportHash,
		arg.RowCountJobs,
		arg.RowCountInvoices,
		arg.Status,
	)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.JobReportFilename,
		&i.InvoiceReportFilename,
		&i.JobReportHash,
		&i.InvoiceReportHash,
		&i.ImportedAt,
		&i.RowCountJobs,
		&i.RowCountInvoices,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getImportBatchByHashes = `-- name: GetImportBatchByHashes :one
SELECT id, job_report_filename, invoice_report_filename, job_report_hash, invoice_report_hash, imported_at, row_count_jobs, row_count_invoices, status, error_message, created_at FROM import_batches
WHERE job_report_hash = $1 AND invoice_report_hash = $2
LIMIT 1
`

type GetImportBatchByHashesParams struct {
	JobReportHash     string `json:"job_report_hash"`
	InvoiceReportHash string `json:"invoice_report_hash"`
}

func (q *Queries) GetImportBatchByHashes(ctx context.Context, arg GetImportBatchByHashesParams) (ImportBatch, error) {
	row := q.db.QueryRowContext(ctx, getImportBatchByHashes, arg.JobReportHash, arg.InvoiceReportHash)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.JobReportFilename,
		&i.InvoiceReportFilename,
		&i.JobReportHash,
		&i.InvoiceReportHash,
		&i.ImportedAt,
		&i.RowCountJobs,
		&i.RowCountInvoices,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listImportBatches = `-- name: ListImportBatches :many
SELECT id, job_report_filename, invoice_report_filename, job_report_hash, invoice_report_hash, imported_at, row_count_jobs, row_count_invoices, status, error_message, created_at FROM import_batches
ORDER BY imported_at DESC
LIMIT $1
`

func (q *Queries) ListImportBatches(ctx context.Context, limit int32) ([]ImportBatch, error) {
	rows, err := q.db.QueryContext(ctx, listImportBatches, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportBatch{}
	for rows.Next() {
		var i ImportBatch
		if err := rows.Scan(
			&i.ID,
			&i.JobReportFilename,
			&i.InvoiceReportFilename,
			&i.JobReportHash,
			&i.InvoiceReportHash,
			&i.ImportedAt,
			&i.RowCountJobs,
			&i.RowCountInvoices,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImportBatchStatus = `-- name: UpdateImportBatchStatus :exec
UPDATE import_batches
SET status = $2, error_message = $3
WHERE id = $1
`

type UpdateImportBatchStatusParams struct {
	ID           int64          `json:"id"`
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
}

func (q *Queries) UpdateImportBatchStatus(ctx context.Context, arg UpdateImportBatchStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateImportBatchStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
