// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoices.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/shopspring/decimal"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    id, job_id, import_batch_id,
    invoice_date, invoice_status, invoice_type, invoice_summary,
    total, balance, payments,
    material_costs, equipment_costs, purchase_order_costs, return_costs, costs_total,
    material_retail, material_markup, equipment_retail, equipment_markup,
    labor, labor_pay, labor_burden, total_labor_costs,
    income, discount_total, is_adjustment
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26
)
RETURNING id, job_id, import_batch_id, invoice_date, invoice_status, invoice_type, invoice_summary, total, balance, payments, material_costs, equipment_costs, purchase_order_costs, return_costs, costs_total, material_retail, material_markup, equipment_retail, equipment_markup, labor, labor_pay, labor_burden, total_labor_costs, income, discount_total, is_adjustment, created_at
`

type CreateInvoiceParams struct {
	ID                 int64           `json:"id"`
	JobID              int64           `json:"job_id"`
	ImportBatchID      int64           `json:"import_batch_id"`
	InvoiceDate        time.Time       `json:"invoice_date"`
	InvoiceStatus      sql.NullString  `json:"invoice_status"`
	InvoiceType        sql.NullString  `json:"invoice_type"`
	InvoiceSummary     sql.NullString  `json:"invoice_summary"`
	Total              decimal.Decimal `json:"amount"`
	Balance            decimal.Decimal `json:"amount"`
	Payments           decimal.Decimal `json:"amount"`
	MaterialCosts      decimal.Decimal `json:"amount"`
	EquipmentCosts     decimal.Decimal `json:"amount"`
	PurchaseOrderCosts decimal.Decimal `json:"amount"`
	ReturnCosts        decimal.Decimal `json:"amount"`
	CostsTotal         decimal.Decimal `json:"amount"`
	MaterialRetail     decimal.Decimal `json:"amount"`
	MaterialMarkup     decimal.Decimal `json:"amount"`
	EquipmentRetail    decimal.Decimal `json:"amount"`
	EquipmentMarkup    decimal.Decimal `json:"amount"`
	Labor              decimal.Decimal `json:"amount"`
	LaborPay           decimal.Decimal `json:"amount"`
	LaborBurden        decimal.Decimal `json:"amount"`
	TotalLaborCosts    decimal.Decimal `json:"amount"`
	Income             decimal.Decimal `json:"amount"`
	DiscountTotal      decimal.Decimal `json:"amount"`
	IsAdjustment       bool            `json:"is_adjustment"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, createInvoice,
		arg.ID,
		arg.JobID,
		arg.ImportBatchID,
		arg.InvoiceDate,
		arg.InvoiceStatus,
		arg.InvoiceType,
		arg.InvoiceSummary,
		arg.Total,
		arg.Balance,
		arg.Payments,
		arg.MaterialCosts,
		arg.EquipmentCosts,
		arg.PurchaseOrderCosts,
		arg.ReturnCosts,
		arg.CostsTotal,
		arg.MaterialRetail,
		arg.MaterialMarkup,
		arg.EquipmentRetail,
		arg.EquipmentMarkup,
		arg.Labor,
		arg.LaborPay,
		arg.LaborBurden,
		arg.TotalLaborCosts,
		arg.Income,
		arg.DiscountTotal,
		arg.IsAdjustment,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ImportBatchID,
		&i.InvoiceDate,
		&i.InvoiceStatus,
		&i.InvoiceType,
		&i.InvoiceSummary,
		&i.Total,
		&i.Balance,
		&i.Payments,
		&i.MaterialCosts,
		&i.EquipmentCosts,
		&i.PurchaseOrderCosts,
		&i.ReturnCosts,
		&i.CostsTotal,
		&i.MaterialRetail,
		&i.MaterialMarkup,
		&i.EquipmentRetail,
		&i.EquipmentMarkup,
		&i.Labor,
		&i.LaborPay,
		&i.LaborBurden,
		&i.TotalLaborCosts,
		&i.Income,
		&i.DiscountTotal,
		&i.IsAdjustment,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoicesForJob = `-- name: GetInvoicesForJob :many
SELECT id, job_id, import_batch_id, invoice_date, invoice_status, invoice_type, invoice_summary, total, balance, payments, material_costs, equipment_costs, purchase_order_costs, return_costs, costs_total, material_retail, material_markup, equipment_retail, equipment_markup, labor, labor_pay, labor_burden, total_labor_costs, income, discount_total, is_adjustment, created_at FROM invoices
WHERE job_id = $1
ORDER BY invoice_date DESC
`

func (q *Queries) GetInvoicesForJob(ctx context.Context, jobID int64) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, getInvoicesForJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ImportBatchID,
			&i.InvoiceDate,
			&i.InvoiceStatus,
			&i.InvoiceType,
			&i.InvoiceSummary,
			&i.Total,
			&i.Balance,
			&i.Payments,
			&i.MaterialCosts,
			&i.EquipmentCosts,
			&i.PurchaseOrderCosts,
			&i.ReturnCosts,
			&i.CostsTotal,
			&i.MaterialRetail,
			&i.MaterialMarkup,
			&i.EquipmentRetail,
			&i.EquipmentMarkup,
			&i.Labor,
			&i.LaborPay,
			&i.LaborBurden,
			&i.TotalLaborCosts,
			&i.Income,
			&i.DiscountTotal,
			&i.IsAdjustment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
