// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package db

import (
	"context"

	"github.com/shopspring/decimal"
)

const getAllJobMetrics = `-- name: GetAllJobMetrics :many
SELECT 
    job_id,
    revenue,
    total_costs,
    gross_profit,
    gross_margin_pct,
    invoice_count,
    has_adjustment
FROM job_metrics
`

type GetAllJobMetricsRow struct {
	JobID          string          `json:"job_id"`
	Revenue        string          `json:"revenue"`
	TotalCosts     string          `json:"total_costs"`
	GrossProfit    string          `json:"gross_profit"`
	GrossMarginPct decimal.Decimal `json:"gross_margin_pct"`
	InvoiceCount   int32           `json:"invoice_count"`
	HasAdjustment  bool            `json:"has_adjustment"`
}

func (q *Queries) GetAllJobMetrics(ctx context.Context) ([]GetAllJobMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllJobMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllJobMetricsRow{}
	for rows.Next() {
		var i GetAllJobMetricsRow
		if err := rows.Scan(
			&i.JobID,
			&i.Revenue,
			&i.TotalCosts,
			&i.GrossProfit,
			&i.GrossMarginPct,
			&i.InvoiceCount,
			&i.HasAdjustment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTechnicianIDs = `-- name: GetAllTechnicianIDs :many
SELECT id FROM technicians
`

func (q *Queries) GetAllTechnicianIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getAllTechnicianIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvoicesForMetrics = `-- name: GetInvoicesForMetrics :many
SELECT 
    id,
    job_id,
    costs_total,
    is_adjustment
FROM invoices
WHERE import_batch_id = $1
`

type GetInvoicesForMetricsRow struct {
	ID           string          `json:"id"`
	JobID        string          `json:"job_id"`
	CostsTotal   decimal.Decimal `json:"costs_total"`
	IsAdjustment bool            `json:"is_adjustment"`
}

func (q *Queries) GetInvoicesForMetrics(ctx context.Context, importBatchID int64) ([]GetInvoicesForMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, getInvoicesForMetrics, importBatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInvoicesForMetricsRow{}
	for rows.Next() {
		var i GetInvoicesForMetricsRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.CostsTotal,
			&i.IsAdjustment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobTechniciansForBatch = `-- name: GetJobTechniciansForBatch :many
SELECT 
    jt.job_id,
    jt.technician_id,
    jt.role
FROM job_technicians jt
JOIN jobs j ON jt.job_id = j.id
WHERE j.import_batch_id = $1
`

type GetJobTechniciansForBatchRow struct {
	JobID        string `json:"job_id"`
	TechnicianID int64  `json:"technician_id"`
	Role         string `json:"role"`
}

func (q *Queries) GetJobTechniciansForBatch(ctx context.Context, importBatchID int64) ([]GetJobTechniciansForBatchRow, error) {
	rows, err := q.db.QueryContext(ctx, getJobTechniciansForBatch, importBatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetJobTechniciansForBatchRow{}
	for rows.Next() {
		var i GetJobTechniciansForBatchRow
		if err := rows.Scan(&i.JobID, &i.TechnicianID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobsForMetrics = `-- name: GetJobsForMetrics :many

SELECT 
    id,
    status,
    jobs_subtotal
FROM jobs
WHERE import_batch_id = $1
`

type GetJobsForMetricsRow struct {
	ID           string          `json:"id"`
	Status       string          `json:"status"`
	JobsSubtotal decimal.Decimal `json:"jobs_subtotal"`
}

// Queries for fetching data needed by Go-side metrics calculations
func (q *Queries) GetJobsForMetrics(ctx context.Context, importBatchID int64) ([]GetJobsForMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, getJobsForMetrics, importBatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetJobsForMetricsRow{}
	for rows.Next() {
		var i GetJobsForMetricsRow
		if err := rows.Scan(&i.ID, &i.Status, &i.JobsSubtotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobsForTechnicianMetrics = `-- name: GetJobsForTechnicianMetrics :many
SELECT 
    id,
    status,
    jobs_subtotal,
    total_hours_worked,
    COALESCE(estimate_count, 0) as estimate_count,
    is_opportunity,
    is_converted
FROM jobs
WHERE import_batch_id = $1
`

type GetJobsForTechnicianMetricsRow struct {
	ID               string          `json:"id"`
	Status           string          `json:"status"`
	JobsSubtotal     decimal.Decimal `json:"jobs_subtotal"`
	TotalHoursWorked decimal.Decimal `json:"total_hours_worked"`
	EstimateCount    int32           `json:"estimate_count"`
	IsOpportunity    bool            `json:"is_opportunity"`
	IsConverted      bool            `json:"is_converted"`
}

func (q *Queries) GetJobsForTechnicianMetrics(ctx context.Context, importBatchID int64) ([]GetJobsForTechnicianMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, getJobsForTechnicianMetrics, importBatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetJobsForTechnicianMetricsRow{}
	for rows.Next() {
		var i GetJobsForTechnicianMetricsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.JobsSubtotal,
			&i.TotalHoursWorked,
			&i.EstimateCount,
			&i.IsOpportunity,
			&i.IsConverted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
