// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/shopspring/decimal"
)

type Customer struct {
	ID            int64          `json:"id"`
	CustomerName  string         `json:"customer_name"`
	CustomerType  sql.NullString `json:"customer_type"`
	CustomerCity  sql.NullString `json:"customer_city"`
	CustomerState sql.NullString `json:"customer_state"`
	CustomerZip   sql.NullString `json:"customer_zip"`
	LocationCity  sql.NullString `json:"location_city"`
	LocationState sql.NullString `json:"location_state"`
	LocationZip   sql.NullString `json:"location_zip"`
	FirstJobDate  sql.NullTime   `json:"first_job_date"`
	LastJobDate   sql.NullTime   `json:"last_job_date"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type ImportBatch struct {
	ID                    int64          `json:"id"`
	JobReportFilename     string         `json:"job_report_filename"`
	InvoiceReportFilename string         `json:"invoice_report_filename"`
	JobReportHash         string         `json:"job_report_hash"`
	InvoiceReportHash     string         `json:"invoice_report_hash"`
	ImportedAt            time.Time      `json:"imported_at"`
	RowCountJobs          int32          `json:"row_count_jobs"`
	RowCountInvoices      int32          `json:"row_count_invoices"`
	Status                string         `json:"status"`
	ErrorMessage          sql.NullString `json:"error_message"`
	CreatedAt             time.Time      `json:"created_at"`
}

type Invoice struct {
	ID                 int64           `json:"id"`
	JobID              int64           `json:"job_id"`
	ImportBatchID      int64           `json:"import_batch_id"`
	InvoiceDate        time.Time       `json:"invoice_date"`
	InvoiceStatus      sql.NullString  `json:"invoice_status"`
	InvoiceType        sql.NullString  `json:"invoice_type"`
	InvoiceSummary     sql.NullString  `json:"invoice_summary"`
	Total              decimal.Decimal `json:"amount"`
	Balance            decimal.Decimal `json:"amount"`
	Payments           decimal.Decimal `json:"amount"`
	MaterialCosts      decimal.Decimal `json:"amount"`
	EquipmentCosts     decimal.Decimal `json:"amount"`
	PurchaseOrderCosts decimal.Decimal `json:"amount"`
	ReturnCosts        decimal.Decimal `json:"amount"`
	CostsTotal         decimal.Decimal `json:"amount"`
	MaterialRetail     decimal.Decimal `json:"amount"`
	MaterialMarkup     decimal.Decimal `json:"amount"`
	EquipmentRetail    decimal.Decimal `json:"amount"`
	EquipmentMarkup    decimal.Decimal `json:"amount"`
	Labor              decimal.Decimal `json:"amount"`
	LaborPay           decimal.Decimal `json:"amount"`
	LaborBurden        decimal.Decimal `json:"amount"`
	TotalLaborCosts    decimal.Decimal `json:"amount"`
	Income             decimal.Decimal `json:"amount"`
	DiscountTotal      decimal.Decimal `json:"amount"`
	IsAdjustment       bool            `json:"is_adjustment"`
	CreatedAt          time.Time       `json:"created_at"`
}

type Job struct {
	ID                 int64           `json:"id"`
	CustomerID         int64           `json:"customer_id"`
	ImportBatchID      int64           `json:"import_batch_id"`
	JobType            string          `json:"job_type"`
	BusinessUnit       sql.NullString  `json:"business_unit"`
	Status             string          `json:"status"`
	JobCreationDate    sql.NullTime    `json:"job_creation_date"`
	JobScheduleDate    sql.NullTime    `json:"job_schedule_date"`
	JobCompletionDate  sql.NullTime    `json:"job_completion_date"`
	AssignedTechnician sql.NullString  `json:"assigned_technician"`
	SoldByTechnician   sql.NullString  `json:"sold_by_technician"`
	BookedBy           sql.NullString  `json:"booked_by"`
	CampaignName       sql.NullString  `json:"campaign_name"`
	CampaignCategory   sql.NullString  `json:"campaign_category"`
	CallCampaign       sql.NullString  `json:"call_campaign"`
	JobsSubtotal       decimal.Decimal `json:"amount"`
	JobTotal           decimal.Decimal `json:"amount"`
	InvoiceID          sql.NullInt64   `json:"invoice_id"`
	TotalHoursWorked   decimal.Decimal `json:"amount"`
	Priority           sql.NullString  `json:"priority"`
	SurveyScore        sql.NullInt32   `json:"survey_score"`
	CreatedAt          time.Time       `json:"created_at"`
}

type JobMetric struct {
	JobID          int64           `json:"job_id"`
	Revenue        decimal.Decimal `json:"amount"`
	TotalCosts     decimal.Decimal `json:"amount"`
	GrossProfit    decimal.Decimal `json:"amount"`
	GrossMarginPct decimal.Decimal `json:"amount"`
	InvoiceCount   int32           `json:"invoice_count"`
	HasAdjustment  bool            `json:"has_adjustment"`
	CalculatedAt   time.Time       `json:"calculated_at"`
}
